[WIP] New object management
betagouv/euphrosyne pull request #105
Opened 2022-02-04 09:24 UTC by wiwski

2022-02-14 16:39 UTC, wiwski commented on lab/assets/js/pages/object-group.js
> +  django.jQuery(document).on("formset:added", onFormsetChange);
A essayer en vanilla

2022-02-17 12:49 UTC, lajarre commented
J'ai créé une PR pour fixer le soucis de locale: dans l'état actuel des choses on ne peut pas créer de run sur Scalingo à cause de ça, si on est en français.

A part ça, je me suis rendu compte qu'il est possible d'avoir des "stale" objects, si on les crée dans la popup de création (à l'intérieur du Run), mais qu'on ne sauvegarde pas la page. A mon avis c'est assez lié au fonctionnement de Django admin. A voir comment on pourrait réduire le pb plus tard.  
Exemple: https://euphrosyne-staging-pr105.osc-fr1.scalingo.io/admin/lab/objectgroup/10/change/

2022-02-18 00:03 UTC, lajarre requested changes

2022-02-18 00:03 UTC, lajarre commented on lab/forms.py
> +                )
Il me semble qu'il y a encore un soucis avec ce formulaire avec le scénario suivant:

- démarrer une création de groupe d'objets
- aller dans l'onglet Groupe
- différentier les objets
- supprimer le 2e objet
- mettre un libellé dans le groupe et un autre libellé différent dans l'objet unique restant en bas
- sauvegarder: ça marche
- on voit:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/1884912/154591540-f2577812-06d6-4b36-b880-a78cf096a2bb.png">

IMHO la bonne solution est d'avoir un backend un peu défensif et totalement inambigü. Pour ça, on peut forcer les champs à être totalement raccords comme suit:

- quand on crée un groupe avec un seul objet (peu importe que le bouton "différentier" ait été cliqué ou non), on prend le libellé du groupe et on le recopie dans l'objet. Idem pour inventaire et collection
- quand on crée un groupe avec plusieurs objets
    - on ne recopie pas le libellé du groupe dans les objets
    - si collection du groupe est non-vide, on la recopie dans tous les `collection` des objets
    - idem pour inventaire.

Honnêtement même avec cette solution je trouve ce qu'est encore compliqué en termes de signification des données, car le libellé du groupe et le libellé de l'objet se mêlent dans le cas un seul objet… Mais c'est acceptable.

Ensuite au front-end de s'adapter à cela, ça devrait découler assez logiquement.

Tu en penses quoi?

2022-02-22 16:12 UTC, wiwski commented on lab/assets/js/pages/object-group.js
> +  document
> je pense qu'il serait bien d'au moins donner des indicateurs visuels, par exemple en grisant les champs

Yes, d'accord avec toi.

> Est-ce qu'on ne pourrait pas également disable le champs collection du groupe (idem pour inventory) dans le cas où au moins un objet a déjà le groupe rempli?

Je ne pense pas que ce soit ce qu'on veut car on peut imaginer utiliser la valeur du groupe pour les objets individuels qui n'ont pas de numéro de collection ou d'inventaire spécifié. En plus, ça devient beaucoup plus complexe à gérer.
Honnêtement je pense pas que ce soit très grave d'avoir une interface assez libre dans la saisie pour l'instant. Et on a déjà beaucoup passé de temps à tatonner sur ce formulaire, je propose qu'on sorte quelque chose, même si on sait que c'est imparfait, et qu'on corrige en ayant des vrais retours et en prenant le temps de refaire des maquettes.

2022-02-22 16:27 UTC, wiwski commented on lab/admin/object.py
> +                form.fields["collection"].widget.attrs["disabled"] = bool(
Il me semble qu'il n'y a pas d'événement correspondant à la fin du chargement du formset. Ca rend l'initialisation en JS compliqué.

2022-02-22 16:32 UTC, wiwski commented on lab/assets/js/object/form.js
> +    getObjectCountField().style.display = "none";
C'est ce qui a dans les maquettes (https://www.notion.so/Reprendre-la-vue-objet-9c571d2f297e42458e782138b72e00bc).
Même remarque qu'en haut. Fions-nous aux maquettes pour le moment et on fera des ajustements plus tard.

2022-02-22 16:43 UTC, wiwski commented on lab/forms.py
> +                    {"class": "vIntegerField"}
J'ai l'impression qu'elle ne sert pas à grand chose, je l'enlève

2022-02-24 18:23 UTC, lajarre commented on lab/assets/js/object/form.js
> +    getObjectCountField().style.display = "none";
Ok sur le fait que ce n'est pas bloquant pour merger, je suis 100% d'accord.

Ceci dit, ce n'est pas étonnant que les maquettes ne soient pas "au courant" de ce genre de problème vu qu'elles ne sont pas dynamiques. Il est donc de la responsabilité des devs de faire un retour côté design et essayer de trouver une solution (si possible pérenne, à mon avis il y a des best practices), voire même de proposer directement la solution best-practice la plus évidente pour ne pas perdre de temps.

2022-02-24 18:55 UTC, lajarre commented on lab/forms.py
> +                )
Hm… Je viens de re-faire le test et en effet on ne voit plus le "Différencier les objets" (le JS le cache bien), mais en revanche je retrouve bien exactement l'état décrit ci-dessus dans la base de données.

Ce qui me pose soucis avec cette situation c'est la fragilité du système: comment un dev futur va-t-il savoir quoi utiliser entre objectgroup.label et object.label quand ceux-ci sont différents?

> quand on crée un groupe avec un seul objet (peu importe que le bouton "différentier" ait été cliqué ou non), on prend le libellé du groupe et on le recopie dans l'objet. Idem pour inventaire et collection

⬆️ cette solution me semble simple et efficace. Tu en penses quoi?

2022-02-24 19:07 UTC, lajarre commented on lab/assets/js/pages/object-group.js
> +  document
Ok pour merger dans l'état sur ce point.

2022-03-05 16:05 UTC, lajarre commented on lab/forms.py
> +                )
Ok pour la solution de renvoyer une erreur!

2022-03-05 16:05 UTC, lajarre approved these changes

2022-03-09 10:20 UTC, merged