Run status upgrade
betagouv/euphrosyne pull request #114
Opened 2022-03-05 16:06 UTC by lajarre

2022-03-05 16:48 UTC, lajarre commented
nb: le dernier commit est à regarder à part (il est dû à un pb avec pylint-django)

https://github.com/betagouv/euphrosyne/pull/114/commits/c48fffa461c1bc84d319c46c076d17299b951a95

2022-03-05 16:48 UTC, lajarre commented
@wiwski à review

2022-03-07 10:13 UTC, wiwski requested changes

2022-03-07 10:49 UTC, wiwski requested changes

2022-03-07 19:41 UTC, lajarre commented on locale/fr/LC_MESSAGES/django.po
> +<<<<<<< HEAD
a re-review sur la nouvelle PR.

2022-03-07 19:44 UTC, lajarre commented on lab/migrations/0016_run_new_status.py
> +# Generated by Django 4.0.1 on 2022-02-21 18:33
yes.

2022-03-07 20:24 UTC, lajarre commented on lab/templates/admin/lab/run/change_list.html
> +<div class="add-row align-right">
ok

2022-03-07 22:10 UTC, lajarre commented on lab/admin/run_actions.py
> +def change_state(_modeladmin, request, queryset):
good catch :)

2022-03-07 22:48 UTC, lajarre commented on lab/assets/js/run/changelist.js
> +    getRunChangeStateActionButton().innerHTML = card.dataset.changestateaction;
ok

2022-03-07 22:48 UTC, lajarre commented on lab/assets/js/run/changelist.js
> +    getRunChangeStateActionButton().title = card.dataset.changestateaction;
ok

2022-03-07 22:49 UTC, lajarre commented on lab/static/css/admin/run.css
> +#run-changestate-action {
ok

2022-03-07 22:49 UTC, lajarre commented on lab/static/css/admin/run.css
> +  border: 4px solid var(--breadcrumbs-bg);
j'ai finalement mis 3px comme sur le Figma

2022-03-07 22:50 UTC, lajarre commented on lab/assets/js/pages/run.js
> +import { getMethodInputs, toggleSubFieldsWrapper } from "../run/methods.js";
Ah. Je ne peux plus accéder à l'env scalingo. Peux-tu m'y réinviter stp avec mon adresse gmail?

2022-03-07 23:08 UTC, lajarre commented on lab/assets/js/pages/run.js
> +import { getMethodInputs, toggleSubFieldsWrapper } from "../run/methods.js";
ça devrait être bon mnt

2022-03-08 11:18 UTC, merged