Feature/top menu
betagouv/euphrosyne pull request #122
Opened 2022-03-16 19:01 UTC by johnoppenheimer

Côté top header, pas de profile Picture pour le moment donc pas affichée pour l’utilisateur connecté, ni sur project leader et dnc pas non plus de partie project members
Comparé au design, j'ai aussi rename « Project leader » en « Leader » car dispo dans les trads (et ça colle aussi à ce qu'on trouve dans le formulaire).

J'en ai aussi profiter pour faire des modifs sur la sidenav.

2022-03-17 17:35 UTC, wiwski requested changes
Le rendu est vraiment propre :tada: 

Je vois juste deux trucs :
- la sidenav est blanche chez moi (thème clair) et ne se voit pas
- le block `messages` est pas fait pour accueillir la top nav. Je pense qu'on a pas le choix que de reprendre tout le fichier `base.html` comme tu avais commencé à le faire...

2022-03-17 17:35 UTC, wiwski commented on euphrosyne/assets/css/components/nav.css
> +  background-color: var(--g-500);
La sidebar n'apparaît plus chez moi, j'imagine que c'est une question de thème sombre / clair
![image](https://user-images.githubusercontent.com/20670382/158853077-08d236fc-8061-4f0e-bcb3-20ac3c596eeb.png)

2022-03-17 17:35 UTC, wiwski commented on euphrosyne/templates/admin/base.html
> +{% block messages %}
Je pense pas que ce soit ouf de mettre ça dans le block `messages`. 
Notamment parce que ça fait ça sur la page de login : 
![image](https://user-images.githubusercontent.com/20670382/158856563-f3b088e6-7318-42c1-95e8-ee551d333541.png)

J'ai bien l'impression qu'on va devoir faire ce que tu avais fait au début, override tout le fichier `base.html` car je ne vois pas où le rentrer sinon

2022-03-17 17:35 UTC, wiwski commented on euphrosyne/templates/admin/base.html
> +    <div id="top-header" class="fr-pr-5v">
Juste une suggestion, si tu ajoutes la class `fr-header`, ça ajoute un shadow qui rend le truc plus lisble. Qu'est-ce que tu en penses ?

2022-03-17 17:35 UTC, wiwski commented on euphrosyne/templates/admin/sidebar/main_sidebar.html
>          {% url 'admin:lab_project_changelist' as project_url %}
Je pense que la manière la plus Django-iste serait de créer un tag `nav_items` qui appelle lui-même chaque `nav-item`

2022-03-17 17:35 UTC, wiwski commented on lab/templates/admin/lab/project/change_form.html
>  {% extends "admin/change_form.html" %}
Tu changes quelque chose dans ce fichier ?

2022-03-17 17:35 UTC, wiwski commented on locale/fr/LC_MESSAGES/django.po
> +msgstr ""
On peut ajouter la trad ici

2022-03-17 17:53 UTC, johnoppenheimer commented on euphrosyne/assets/css/components/nav.css
> +  background-color: var(--g-500);
Ooh indeed ça m'a échappé! C'est bien sensé être la même couleur

2022-03-17 17:57 UTC, johnoppenheimer commented on lab/templates/admin/lab/project/change_form.html
>  {% extends "admin/change_form.html" %}
Yes! Ajout du `block top_header`, et juste une re-indent du fichier

2022-03-19 09:40 UTC, wiwski requested changes
J'ai laissé d'autres commentaires. Désolé si ça paraît lourd mais c'est l'occasion de te présenter toutes les reflexions qu'on a eu en amont !

2022-03-19 09:40 UTC, wiwski commented on euphrosyne/assets/css/base.css
> +.breadcrumbs {
On peut le supprimer directement dans `base.html` si on override tout le template

2022-03-19 09:40 UTC, wiwski commented on lab/templatetags/nav.py
> +    print(current_path)
T'as du oublier ça :-)

2022-03-19 09:40 UTC, wiwski commented on euphrosyne/templates/admin/sidebar/main_sidebar.html
>      <h1 class="sidebar-title">{{ site_header|default:_("Django") }}</h1>
On peut virer le `|default:_("Django")` comme ça on aura pas la trad

2022-03-19 09:40 UTC, wiwski commented on scripts/makeallmessages.sh
> +pipenv run "$PROJECT_DIR"/manage.py makemessages --all --verbosity 0 --no-location --no-obsolete
T'as du oublier de revert ça non ?

2022-03-19 09:40 UTC, wiwski commented on webpack.config.js
> +  plugins: [new MiniCssExtractPlugin()],
On utilise pas purgecss finalement ?

2022-03-19 09:40 UTC, wiwski commented on euphrosyne/assets/css/components/header.css
> +#top-header {
Je te laisse ce commentaire à ta discretion mais on était parti dans l'optique d'utiliser des `rem` plutôt que des `px` pour tout ce qui est relatif à la largeur des éléments

2022-03-21 16:09 UTC, johnoppenheimer commented on lab/objects/nav.py
> +class NavItem(object):
J'y ai pensé, mais je voulais mettre des valeurs par default

2022-03-21 16:52 UTC, johnoppenheimer commented on webpack.config.js
> +  plugins: [new MiniCssExtractPlugin()],
Je l'avais enlever car j'avais l'impression d'avoir quelques soucis de config concernant la detection des styles du DSFR, mais semblerait que ce soit bon donc je vais le remettre

2022-03-21 20:17 UTC, johnoppenheimer commented on lab/objects/nav.py
> +from typing import List
indeed! J'avais mal vu le contenu du dossier, je bouge ça

2022-03-22 15:35 UTC, wiwski commented on webpack.config.js
> +  plugins: [new MiniCssExtractPlugin()],
Ouai de mon côté il faut que je relance webpack à chaque fois que j'utilise une nouvelle classe du DSFR

2022-03-24 16:23 UTC, merged