📃 Add precise Run model fields
betagouv/euphrosyne pull request #48
Opened 2021-11-18 16:22 UTC by lajarre

* Add Analysis techniques and related choices configuration in a yaml file.
* Add fields to the Run model and related sub-models.
* Run admin:
  * Validations in ModelAdmin forms.
  * Run edition apart from status into RunModelAdmin.
  * Make use of hidden input to prefill Project in Run view.
  * Adapt permissions.

2021-11-24 11:12 UTC, wiwski requested changes

2021-11-24 11:12 UTC, wiwski commented on lab/tests/admin/test_run_admin.py
> +        self.project_leader_user = factories.StaffUserFactory()
Ca ne simpliefirait pas d'écrire ? 
```
        self.staff_user = factories.StaffUserFactory()
        self.project_leader_user = factories.StaffUserFactory()
        self.existing_project = factories.ProjectFactory()
```
Car `project_leader_user` n'est ici pas vraiment un leader non ?

2021-11-24 11:12 UTC, wiwski commented on lab/tests/factories.py
> +import factory
Top ! Ca va nous simplifier la vie

2021-11-24 11:12 UTC, wiwski commented on lab/tests/forms/run/test_run_status_form.py
> +@pytest.mark.parametrize(
Je connaissais pas ce decorateur :+1:

2021-11-24 11:12 UTC, wiwski commented on lab/widgets.py
> +class DisabledSelectWithHidden(Select):
Sympa,je pense que  je vais l'utiliser pour la partie Object

2021-11-24 11:41 UTC, lajarre commented on lab/templates/admin/edit_inline/stacked_run_in_project.html
> +<div class="inline-related"><h3><a class="button" href="{% url 'admin:lab_run_add' %}?project={{ object_id }}">{% translate "Add" %}</a></h3></div>
bien mieux!

2021-11-24 11:45 UTC, lajarre commented on lab/forms.py
> +class RunDetailsForm(ModelForm):
good catch

2021-11-24 12:43 UTC, lajarre commented
J'ai repris tout tes commentaires @wiwski sauf celui sur le front-end de l'inline, que je vais tenter dans une autre PR pour pouvoir échanger desssu tranquillement.  
Note: j'ai aussi retiré le premier commit que j'avais fait (inutile) et ajouté un commit au tout début avec `./scripts/makeallmessages.sh`, je te laisse regarder.

2021-11-24 13:09 UTC, lajarre commented on lab/forms.py
> +                    "The run can't start while the Run fields aren't defined.",
Oups j'avais zappé ce comment, je viens de push un correctif.

2021-11-25 08:31 UTC, wiwski commented
Ok, super.
Est-ce que tu as vu les commentaires suivants également ? 
https://github.com/betagouv/euphrosyne/pull/48#discussion_r755908356
https://github.com/betagouv/euphrosyne/pull/48#discussion_r755910931
https://github.com/betagouv/euphrosyne/pull/48#discussion_r755914556

2021-11-25 08:40 UTC, lajarre commented on lab/forms.py
> +class RunStatusMemberForm(RunStatusBaseForm):
Yes bonne idée (je ne sais pas pourquoi je n'ai pas vu ce comment avant, peut-être était-il collapsé)?

2021-11-25 08:41 UTC, lajarre commented on lab/models/__init__.py
Oui en effet, j'ai fait ça uniquement pour éviter les conflits, mais j'aurais pu mettre les choses dans `lab/models/project.py` pour l'instant, ce sera plus propre. Ensuite voyons quand on fait le refacto en sous-apps.

2021-11-25 08:43 UTC, lajarre commented on lab/models/run.py
> +with open(Path(__file__).parent / "run-choices-config.yaml") as f:
Je suis d'accord dans le principe mais je voulait laisser ce morceau pour la PR qui viendra se poser au-dessus, car après tout je vais reprendre totalement la partie config à cette occasion. C'est du code temporaire.

2021-11-25 09:09 UTC, wiwski approved these changes

2021-11-25 10:31 UTC, merged