Send invitation again in user invitation admin
betagouv/euphrosyne pull request #55
Opened 2021-11-22 15:36 UTC by wiwski

2021-11-24 23:34 UTC, lajarre requested changes

2021-11-24 23:34 UTC, lajarre commented on euphro_auth/tests/admin/test_send_invitation_mail_action.py
> +        assert any(
Pas trop convaincu de l'utilité des tests sur `messages.WARNING` et `messages.SUCCESS` car on pourrait aisément changer le code de la méthode admin action que tu as ajoutée tout en changeant fortement son comportement sans pour autant faire planter ton test, et inversement. Je serais d'avis de tester uniquement la mail outbox, c'est le seul "vrai side-effect".

2021-11-25 09:29 UTC, wiwski commented on euphro_auth/tests/admin/test_send_invitation_mail_action.py
> +        assert any(
Ok, je vire les deux assert

2021-11-25 23:38 UTC, lajarre approved these changes

2021-12-01 09:26 UTC, merged