Feature/runs details
betagouv/euphrosyne pull request #59
Opened 2021-11-25 23:29 UTC by lajarre

Il s'agit ici de gérer le rapport entre `particle_type` et `energie_in_keV`, avec les datalist.

Je n'ai pas trouvé de moyen de tout mettre dans un seul Field avec plusieurs widgets différents, je me suis vite retrouvé limité car globalement tout est fait pour que 1 field == 1 data point.

Donc finalement, pour la lisibilité, j'ai tout bougé dans une sorte de mini-librairie `controlled_datalist.py`. Il y a un truc un peu olé avec le decorateur de classe et l'appel à la metaclass, mais c'est juste similaire que ce qu'il se passe déjà dans `modelform_factory`. J'ai laissé les tests spécifiques à `RunDetailForm` car pour l'instant pas nécessaire de rendre cela générique.

2021-11-26 09:53 UTC, wiwski requested changes
C'est quasi bon de mon côté !

Deux autres commentaires :
- je crois qu'il manque une migration non ?
- on garde `lab/fields.py` même s'il est vide ?

2021-11-26 09:53 UTC, wiwski commented on lab/controlled_datalist.py
> +"""
Super comme approche ! :+1: 
Est-ce que tu penses pouvoir documenter un peu plus les différentes classes ? Une petite description pour dire quelle classe fait quoi, ça pourra être utiile qu'on on revient dessus dans un petit moment.

2021-11-26 09:53 UTC, wiwski commented on lab/controlled_datalist.py
> +            fields = tuple(cls.Meta.fields) + (
(à ta discrétion) Pour la concaténation, il y a aussi cette méthode que je trouve plus facile à lire : 
```
fields = (*cls.Meta.fields, controller_field_name, controlled_field_name,)
```

2021-11-29 10:44 UTC, lajarre commented
>     * je crois qu'il manque une migration non ?

Non pour le coup pas de migration, c'est seulement une réécriture du form.

>     * on garde `lab/fields.py` même s'il est vide ?

Je vire

2021-11-29 11:56 UTC, lajarre commented on lab/controlled_datalist.py
> +"""
Done

2021-11-29 11:57 UTC, lajarre commented
@wiwski j'ai ajouté des docstrings et fait un petit cleanup. J'ai corrigé une petite erreur de front-end btw.

2021-12-01 09:18 UTC, wiwski approved these changes
C'est bon pour moi ! (juste une typo sur un docstring)

2021-12-01 09:18 UTC, wiwski commented on lab/controlled_datalist.py
> +    controleld integer field with choices displayed in <datalist> elements
_conttroled_ integer

2021-12-01 11:04 UTC, merged