Feature/objects crud
betagouv/euphrosyne pull request #63
Opened 2021-11-29 12:51 UTC by wiwski

2021-12-01 13:55 UTC, wiwski commented on lab/tests/factories.py
> +    energy_in_keV = factory.fuzzy.FuzzyInteger(0, high=10000, step=500)
Je comprends pas pourquoi ça ajoute ces deux lignes qui sont déjà présentes sur `main`

2021-12-06 10:11 UTC, wiwski commented on lab/admin/run.py
> +# Allowance: ADMIN:lab admin, EDITOR:project leader, VIEWER:project member
A supprimer

2021-12-07 00:46 UTC, lajarre requested changes

2021-12-07 00:46 UTC, lajarre commented on lab/admin/object.py
> +            widgets={"materials": TagsInput()},
Pourquoi ne pas mettre ça dans le form?

2021-12-07 00:46 UTC, lajarre commented on lab/tests/forms/object/test_objectgroup_form.py
> +    form.full_clean()
Il me semblait que l'accès à `Form.errors` provoquait l'appel à `full_clean`, non?

2021-12-07 00:46 UTC, lajarre commented on lab/tests/forms/object/test_objectgroup_form.py
> +    assert form.has_error("label")
tu peux ajouter le `code=…`

2021-12-07 00:46 UTC, lajarre commented on lab/forms.py
> +    def __init__(self, **kwargs: Mapping[str, Any]) -> None:
Je crois que tu as oublié le `*args`. J'ai eu une erreur 500 en testant:

```
    form = ModelForm(request.POST, request.FILES, instance=obj)
TypeError: __init__() takes 1 positional argument but 3 were given
ERROR "POST /admin/lab/objectgroup/add/?_to_field=id&_popup=1 HTTP/1.1" 500 122561
```

2021-12-07 00:46 UTC, lajarre commented on lab/static/js/widgets/tags-input.js
> +"use strict";
Y a-t-il peut-être besoin de créditer et faire référence à une lib ou un snippet existant quelque part?

2021-12-07 00:46 UTC, lajarre commented on lab/static/js/admin/object-group.js
> +    groupLabelHiddenInput = document.createElement("input");
Un truc m'échappe: n'y a-t-il pas déjà un `input[name="label"]` dans le formulaire? Pourquoi en rajouter un autre?

2021-12-07 18:11 UTC, wiwski commented on lab/admin/object.py
> +            widgets={"materials": TagsInput()},
Oui je ne sais pas pourquoi j'ai mis ça là ...

2021-12-07 18:13 UTC, wiwski commented on lab/tests/forms/object/test_objectgroup_form.py
> +    form.full_clean()
Ah oui, excact !

2021-12-08 08:28 UTC, wiwski commented on lab/static/js/admin/object-group.js
> +    groupLabelHiddenInput = document.createElement("input");
En fait il y a deux éléments suivant `add_type` : l'input normal qui est généré par Django et un hidden input créé par ce script.
J'aurais pu passer l'input en hidden directement mais ça ne marcherait pas car je passe l'élément parent (qui contient l'input et le label) en `display: none`.

2021-12-08 08:29 UTC, wiwski commented on lab/static/js/widgets/tags-input.js
> +"use strict";
Tu as raison, j'ai totalement zappé de le faire

2021-12-08 08:40 UTC, wiwski commented
@lajarre j'ai fait les modifications et fais quelques modifs, notamment la possibilité de supprimer un objet dans un `objectgroup`

2021-12-08 22:29 UTC, lajarre commented on lab/static/js/widgets/tags-input.js
> +/**
Ca marche pas trop mal mais je vois encore deux problèmes:

- [gêne 4/5] si on oublie de mettre une virgule et qu'on n'a qu'un seul matériau à rentrer, alors ça ne le prend pas en compte et le form refuse. Mais surtout il y a un risque potentiel si on oublie de mettre la virgule pour le dernier matériau alors qu'on a fait une longue liste => data loss discret pour l'utilisateur.
- [gêne 2/5] ça ne marche pas bien quand on va vite ou quand il y a peu de lettres.

Aucun n'est bloquant pour merger, mais ce serait bien je pense de trouver une solution au premier.

2021-12-08 22:39 UTC, lajarre commented on lab/admin/object.py
> +class ObjectInline(admin.TabularInline):
Est-ce qu'on ne devrait pas empêcher l'inline d'ajouter des nouveaux objets quand l'objectgroup est en mode "One object"?

Même question pour la suppression (empêcher la suppression de l'unique objet).

Aussi, quand l'object group est multiple: devrait-on permettre de supprimer tous les objets? Je dirais oui, a priori (donc on laisse comme tel dans ce cas).

2021-12-08 22:39 UTC, lajarre commented on lab/static/js/admin/object-group.js
> +    groupLabelHiddenInput = document.createElement("input");
Ok je vois, mais qu'est-ce qui nous garanti que c'est le bon input qui est envoyé dans le form submit, dans ce cas? Ne vaudrait-il pas mieux supprimer l'input dupliqué en faisant `document.getElementsByName('label').remove()`?

2021-12-08 22:44 UTC, lajarre commented on lab/static/js/admin/object-group.js
> +        for (let i = 1; i <= newObjectRows.length; i++) {
je suis un peu étonné du `<=`, ne tombe-t-on pas out-of-bounds ici?

Un `.shift()` puis `.forEach()` peut-être?

2021-12-11 12:13 UTC, wiwski commented on lab/static/js/widgets/tags-input.js
> +/**
Pour le premier point, j'ai ajouté un event listener sur`blur` (01acd8548c315409dc4e39cfc52912c276be32ed)

2021-12-13 10:50 UTC, merged