Feature/runs methods sql
betagouv/euphrosyne pull request #70
Opened 2021-12-06 11:07 UTC by lajarre

2021-12-13 11:08 UTC, lajarre commented on lab/methods/types.py
> +from pathlib import Path
Vérifier ce qui se passe quand on fait plusieurs imports

2021-12-16 10:55 UTC, wiwski commented on lab/methods/models.py
> +METHODS_FIELDNAMES: list[str] = []
Je pense qu'on peut se passer de ces variables globales en utilisant directement les attributs du Run. Je viens de tester pour ajouter le fieldset dans `run/admin` (tu peux écrire ça plus compact et plus joli mais c'est pour la démonstration) :

```
        ...
        (
            "METHODS",
            {
                "fields": (
                    *(
                        getattr(Run, run_attr).field.name
                        for run_attr in dir(Run)
                        if hasattr(getattr(Run, run_attr), "field")
                        and isinstance(getattr(Run, run_attr).field, MethodBooleanField)
                    ),
                    *(
                        getattr(Run, run_attr).field.name
                        for run_attr in dir(Run)
                        if hasattr(getattr(Run, run_attr), "field")
                        and isinstance(getattr(Run, run_attr).field, DetectorFieldMixin)
                    ),
                    *(
                        getattr(Run, run_attr).field.name
                        for run_attr in dir(Run)
                        if hasattr(getattr(Run, run_attr), "field")
                        and isinstance(getattr(Run, run_attr).field, FiltersCharField)
                    ),
                )
            },
        ),
```

2021-12-16 10:55 UTC, wiwski commented on lab/methods/models.py
> +METHODS_FIELDNAMES: list[str] = []
Une version plus compacte :
```
            {
                "fields": tuple(
                    itertools.chain.from_iterable(
                        (
                            getattr(Run, run_attr).field.name
                            for run_attr in dir(Run)
                            if hasattr(getattr(Run, run_attr), "field")
                            and isinstance(getattr(Run, run_attr).field, field_class)
                        )
                        for field_class in (
                            MethodBooleanField,
                            DetectorFieldMixin,
                            FiltersCharField,
                        )
                    )
                )
            },
```

2021-12-16 10:55 UTC, wiwski commented on lab/methods/models.py
> +METHODS_FIELDNAMES: list[str] = []
En utilisant cette approche, plus besoin des classes `*_FIELDS_REGISTER` ; ça simplifie pas mal

2021-12-16 13:13 UTC, lajarre commented on lab/admin/run.py
> +            "METHODS",
Non c'est un hack, je Check pour la string METHODS dans le template html

2021-12-16 13:17 UTC, lajarre commented on lab/methods/models.py
> +METHODS_FIELDNAMES: list[str] = []
Bonne idée, je vais reprendre ça!

2022-01-03 11:45 UTC, lajarre commented on lab/methods/models.py
> +METHODS_FIELDNAMES: list[str] = []
En fait ce n'est pas possible de se baser uniquement sur des `isinstance` car il me faut créer la liste suivante:

```python
[('method_PIXE', 'detector_LE0'), ('method_PIXE', 'detector_HE1'), ...]
```

Je vais donc être obligé d'avoir recours à la structure `METHODS_DETECTORS` qui vient du fichier de config.

Ceci dit par soucis de simplicité je vais essayer de retirer les variables globales et faire une version avec des classmethod uniquement.

2022-01-04 11:36 UTC, lajarre commented on lab/admin/project.py
> +        (_("Methods"), {"fields": ()}),
Pour l'instant non, j'ai préféré enlever ce fieldset. Ca demande un peu de travail pour essayer de coller à la spec UI, donc à aborder dans une autre PR.

2022-01-04 11:40 UTC, lajarre commented on lab/methods/models.py
> +        next(
Conclusion: j'ai retiré le fichier `config.yaml` et juste injecté les valeurs méthodes / détecteurs et filtres dans le modèle (`MethodModel`). C'est la version sans doute la plus simple et la plus idiomatique Django.

Une autre idée pour la suite si besoin d'éditer plus facilement la configuration méthodes:

- repartir sur un fichier type config.yaml
- le parser dans le `ModelForm` et non dans le `Model`, et créer des champs de formulaire de manière dynamique
- a priori la logique de `Form.clean` et d'affichage devrait rester similaire.

2022-01-04 11:40 UTC, lajarre commented on lab/methods/models.py
> +METHODS_FIELDNAMES: list[str] = []
J'ai repris le travail sur la base de `isinstance` en fait :) mais dans les model ### fields directement.

2022-01-10 11:04 UTC, wiwski requested changes
Quelques remarques mineures.

Bravo pour le travail de réécriture, c'est beaucoup plus lisible et je pense vraiment que c'est une bonne approche :+1:

2022-01-10 23:35 UTC, lajarre commented on euphrosyne/settings.py
> +    print("⚠️  No postgres database, running on SQLite")
A ce point du code les loggers ne sont pas défini comme dans le reste du projet (car c'est settings qui les définit). Donc pour utiliser `logging` il faudrait que je définisse un logger spécifique avec un handler `logging.StreamHandler(sys.stdout)`. Je trouve ça un peu overkill, pour le même résultat. Est-on d'accord d'afficher le contenu des prints dans tous les cas?

De plus, on ne devrait pas voir settings.py comme un module normal: il n'est pas sensé être importé quand on veut, mais seulement par Django au moment de la commande `./manage.py …`. Ca ne me choque pas de faire des `print` ici comme on pourrait le faire dans un script.

Tu en penses quoi?

2022-01-10 23:42 UTC, lajarre commented on lab/static/js/widgets/select-with-free-other.js
> +(function () {
En effet. Il faut introduire eslint et prettier dans la CI je pense. Je le note dans un ticket à part.

2022-01-11 00:23 UTC, lajarre commented on lab/static/js/admin/methods.js
> +(function () {
Ca m'a l'air très bien en effet! A faire dans une PR subséquente.

2022-01-12 16:50 UTC, lajarre commented on lab/tests/factories.py
> +class RunRandomizeAtLeastAMethodFactory(RunFactory):
Oui c'est juste, je retire le random.

2022-01-14 08:03 UTC, wiwski commented on euphrosyne/settings.py
> +    print("⚠️  No postgres database, running on SQLite")
Hmm je vois ce que tu veux dire.
Mais pour bien comprendre, en quoi est-ce que c'est différent d'utiliser le module `logging` ?

```
import logging
...
    else:
         logging.info("⚠️  No postgres database, running on SQLite")
```

C'est similaire à un `print` mais ça permet juste d'avoir plus de contrôle sur ce qui sort.

2022-01-14 08:08 UTC, wiwski approved these changes
C'est bon pour moi :tada: 

Juste un commentaire sur le `print` vs `logging` pour bien comprendre :slightly_smiling_face:

2022-01-14 20:50 UTC, lajarre commented on euphrosyne/settings.py
> +    print("⚠️  No postgres database, running on SQLite")
Après vérification, `logging.info` n'imprime rien quand utilisé dans `settings.py` car le level par défaut est `WARNING`. Donc soit:

- utiliser `logging.warning` que je trouve que ça fait "too much" dans le cas des autres prints que j'ai fait (ceux qui ressemblent à`f"🅸  Using normal database {base_db_name}"`)
- créer une configuration ad-hoc pour le fichier `settings.py`, ce que je trouve dommage et "confusant" car le rôle même de settings est de contenir la définition du dict de configuration `LOGGING`
- ou bien laisser des prints.

Tu sais où mon coeur balance :) Je préfère rester au plus simple par défaut.

Mais en plus, je ne pense pas qu'il faille nécessairement utiliser logging vs print. Dans un script par exemple, faire du `print` et `sys.stdout.write` est tout-à-fait normal. Et on peut considérer `settings.py` comme une sorte de point d'entrée.

2022-01-14 21:02 UTC, merged