💚 Prevent form input loss by editing leader in popup
betagouv/euphrosyne pull request #96
Opened 2022-01-21 16:57 UTC by lajarre

2022-01-28 10:11 UTC, wiwski requested changes
Je ne pense pas que soit une soltution propre sur le long terme mais en attendant ça le fait. Bien joué pour le travail d'adaptation du code en tout cas :+1: 
J'ai juste mis quelques commentaires mineurs

2022-01-28 10:11 UTC, wiwski commented on lab/views/change_leader_view.py
> +            obj = (
Est-ce qu'on ne peut pas utiliser la query ligne 41 ?

2022-01-28 10:11 UTC, wiwski commented on lab/templates/widgets/leader_readonly.html
> +{% if project_id %}
Je mettrais ce `if` dans `admin/project.py` non ?

2022-01-28 10:11 UTC, wiwski commented on lab/static/js/admin/ViewObjectLookups.js
> +/*global SelectBox, interpolate*/
Il faudrait peut-être ajouter en comentaire un lien vers l'implémentation initiale (https://github.com/django/django/blob/492ed60f236d770eb9a6d56d85ff2550bb1ecfff/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js)

2022-01-31 18:10 UTC, lajarre commented on lab/admin/project.py
> +        maybe_user = obj.leader.user if obj.leader else None
J'ai changé pour `user`. C'était pour faire comme https://wiki.haskell.org/Maybe mais pas cohérent ici.

2022-01-31 18:23 UTC, lajarre commented on lab/templates/widgets/leader_readonly.html
> +{% if project_id %}
Yes! Ça y était déjà en fait, j'ai retiré celui-ci.

2022-02-01 15:06 UTC, lajarre commented on lab/views/change_leader_view.py
> +            obj = (
Yes. Finalement j'en ai profité pour reprendre un peu la classe et ajouter/refactor les tests dans `lab/tests/views/test_change_leader_view.py`, je te laisse voir.

2022-02-03 09:29 UTC, wiwski requested changes

2022-02-03 09:29 UTC, wiwski commented on lab/tests/views/test_change_leader_view.py
> +import json
Top la réécriture

2022-02-03 09:46 UTC, lajarre commented on lab/tests/views/test_change_leader_view.py
> +    try:
Yes en effet c'est sans doute mieux.

2022-02-03 10:04 UTC, lajarre commented on lab/tests/views/test_change_leader_view.py
> +    try:
En fait il y avait bien un soucis qui m'a poussé en ce sens: le call à la view va produire une erreur de tentative de connexion à la base de données. J'ai refacto un peu plus pour mieux mocker tout çå.

2022-02-03 10:16 UTC, merged